#!/bin/sh
##############################################################################
#
#   Copyright 2004 The Apache Software Foundation.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################
#
# Small shell script to show how to start/stop Tomcat using jsvc
# If you want to have Tomcat running on port 80 please modify the server.xml
# file:
#
#    <!-- Define a non-SSL HTTP/1.1 Connector on port 80 -->
#    <Connector className="org.apache.catalina.connector.http.HttpConnector"
#               port="80" minProcessors="5" maxProcessors="75"
#               enableLookups="true" redirectPort="8443"
#               acceptCount="10" debug="0" connectionTimeout="60000"/>
#
. /etc/rc.d/init.d/functions
# That is for Tomcat-5.0.x (Apache Tomcat/5.0)
#
# Adapt the following lines to your configuration
JAVA_HOME=/usr/local/jdk{{ jdk_ver }}
CATALINA_HOME=/web/tomcat{{ ver }}_{{ port }}_{{ servername }} 
DAEMON_HOME="$CATALINA_HOME/bin"
JAVA_OPTS="-jvm server -Xms2048M -Xmx2048M -Xverify:none -XX:PermSize=512M -XX:MaxPermSize=512m -XX:+UseAdaptiveSizePolicy -XX:+UseParallelGC -XX:+UseParallelOldGC -XX:NewSize=512m -Xmn512m"
TOMCAT_USER="www"

# for multi instances adapt those lines.
TMP_DIR="$CATALINA_HOME/temp"
PID_FILE="$CATALINA_HOME/logs/jsvc.pid"
CATALINA_BASE=$CATALINA_HOME

CATALINA_OPTS="-Djava.library.path=/home/jfclere/jakarta-tomcat-connectors/jni/native/.libs"
CATALINA_OPTS=""
CLASSPATH=\
$JAVA_HOME/lib/tools.jar:\
$CATALINA_HOME/bin/commons-daemon.jar:\
$CATALINA_HOME/bin/bootstrap.jar:\
$CATALINA_HOME/bin/tomcat-juli.jar 

start() 
{
    # Start Tomcat
    $DAEMON_HOME/jsvc \
    -user $TOMCAT_USER \
    -home $JAVA_HOME \
    -Dcatalina.home=$CATALINA_HOME \
    -Dcatalina.base=$CATALINA_BASE \
    -Djava.io.tmpdir=$TMP_DIR \
    -wait 10 \
    -pidfile $PID_FILE \
    -outfile $CATALINA_HOME/logs/catalina.out \
    -errfile '&1' \
    $JAVA_OPTS \
    $CATALINA_OPTS \
    -cp $CLASSPATH \
    org.apache.catalina.startup.Bootstrap
    # To get a verbose JVM
    #-verbose \
    # To get a debug of jsvc.
    #-debug \
    exit $? 
}
stop() 
{
    # Stop Tomcat
    $DAEMON_HOME/jsvc \
    -stop \
    -pidfile $PID_FILE \
    org.apache.catalina.startup.Bootstrap 
}
#echo $JAVA_HOME
version()
{
        $JAVA_HOME/bin/java -classpath $CATALINA_HOME/lib/catalina.jar org.apache.catalina.util.ServerInfo
        RETVAL=$?
}
rhstatus()
{
        status -p $PID_FILE jsvc
        RETVAL=$?
}
case "$1" in
  start)
        start
    ;;
  stop) 
        stop
        rm -rf  $CATALINA_HOME/work/*
        rm -rf  $CATALINA_HOME/temp/*
    ;;
  restart)
        stop
        ps aux |grep -v grep |grep "$CATALINA_HOME" >/dev/null 2>&1;[[ "$?" -eq 0 ]] && kill $(ps aux|awk '/'$(basename $CATALINA_HOME)'/&& ! /awk/{ORS=" ";print $2}')
        rm -rf  $CATALINA_HOME/work/*
        rm -rf  $CATALINA_HOME/temp/*
        start
    ;;
 version)
        version
   ;;
  status)
        rhstatus
   ;;
  *)
        echo "Usage /etc/init.d/jsvc {start|stop|restart|status|version}"
    ;;
esac
